name: Dev Version

on:
  push:
    branches:
      - dev

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      with:
        ref: main
    - name: Install Semantic Release
      run: npm install semantic-release @semantic-release/github @semantic-release/exec semantic-release-gitmoji -D
    - name: Run Semantic Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload version artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: version
        path: VERSION.txt